stages:
  - lint
  - name: unit-test
    if: branch = develop

dist: xenial
language: node_js
node_js:
  - 12
before_install:
  - export PATH=~/npm/node_modules/.bin:$PATH
install:
  - npm install
script:
  - npm start lint
  - npm start test.unit

jobs:
  include:
    - stage: lint
      name: "Linting"
      script:
        - nps lint

    - stage: unit-test
      name: "Unit testing"
      script:
        - nps test.unit
